const SECTIONS = {
  basics: { label: "R Basics", emoji: "🧱", desc: "Variablen, Datentypen, Vektoren, Zuweisungen" },
  daten: { label: "Daten & Strukturen", emoji: "📊", desc: "Data Frames, Listen, Subsetting, Faktoren" },
  statistik: { label: "Statistik", emoji: "📈", desc: "Mittelwert, t-Test, ANOVA, Korrelation, Regression" },
  visualisierung: { label: "Visualisierung", emoji: "🎨", desc: "ggplot2, Histogramme, Scatter Plots, Boxplots" },
  tidyverse: { label: "Tidyverse", emoji: "🔧", desc: "Pipe, dplyr, filter, mutate, summarise" },
};

const QUESTIONS = [
  // ========== R BASICS ==========
  {
    section: "basics",
    category: "Vektoren",
    context: "Du hast die Stresslevel von 5 Katzen gemessen: Muffin (3), Whiskers (5), Luna (7), Simba (4) und Nala (6).",
    question: "Wie erstellst du daraus einen Vektor in R?",
    code: null,
    options: [
      'stress <- c(3, 5, 7, 4, 6)',
      'stress <- (3, 5, 7, 4, 6)',
      'stress <- vector[3, 5, 7, 4, 6]',
      'stress <- list(3, 5, 7, 4, 6)',
    ],
    correct: 0,
    explanation: 'In R erstellst du Vektoren mit <code>c()</code> ("combine"). Die Funktion verbindet einzelne Werte zu einem Vektor. <code>list()</code> erstellt eine Liste, das ist ein anderer Datentyp.',
  },
  {
    section: "basics",
    category: "Datentypen",
    context: "Du kodierst die Fellfarbe deiner Versuchskatzen für deine Studie.",
    question: "Welchen Datentyp hat dieser Vektor?",
    code: 'fellfarbe <- c("schwarz", "orange", "grau", "weiß")',
    options: ["numeric", "logical", "character", "factor"],
    correct: 2,
    explanation: "Text in Anführungszeichen ergibt den Typ <code>character</code>. Für statistische Analysen würdest du ihn oft in einen <code>factor</code> umwandeln mit <code>factor(fellfarbe)</code>.",
  },
  {
    section: "basics",
    category: "Zuweisung",
    context: "Du speicherst das Durchschnittsgewicht deiner Therapiekatze Luna.",
    question: "Welcher Zuweisungsoperator wird in R am häufigsten verwendet?",
    code: null,
    options: ["<-", "=", ":=", "=="],
    correct: 0,
    explanation: "In R ist <code><-</code> der Standard-Zuweisungsoperator. <code>=</code> funktioniert auch, wird aber eher für Funktionsargumente benutzt. <code>==</code> ist der Vergleichsoperator!",
  },
  {
    section: "basics",
    category: "Logische Operatoren",
    context: "Du suchst Katzen, die älter als 3 UND schwerer als 4kg sind, für deine Adipositas-Studie.",
    question: "Welcher logische Operator verbindet zwei Bedingungen elementweise?",
    code: "katzen[katzen$alter > 3 ___ katzen$gewicht > 4, ]",
    options: ["&&", "&", "AND", "and"],
    correct: 1,
    explanation: "In R gibt es <code>&</code> (elementweise, für Vektoren) und <code>&&</code> (nur erstes Element, für if-Bedingungen). Beim Filtern von Data Frames brauchst du <code>&</code>.",
  },
  {
    section: "basics",
    category: "Funktionen",
    context: "Du schreibst eine Funktion, die den BMI einer Katze berechnet: Gewicht (kg) / Körperlänge (m) zum Quadrat.",
    question: "Welche Syntax ist korrekt?",
    code: null,
    options: [
      "katzen_bmi <- function(gewicht, laenge) { gewicht / laenge^2 }",
      "def katzen_bmi(gewicht, laenge): gewicht / laenge^2",
      "function katzen_bmi(gewicht, laenge) { return gewicht / laenge^2 }",
      "katzen_bmi = (gewicht, laenge) => gewicht / laenge**2",
    ],
    correct: 0,
    explanation: "In R werden Funktionen mit <code>function()</code> erstellt und einer Variablen zugewiesen. Der letzte Ausdruck wird automatisch zurückgegeben. Option B ist Python, C ist JavaScript-artig, D ist eine Arrow Function.",
  },
  {
    section: "basics",
    category: "Packages",
    context: "Du möchtest das tidyverse-Paket benutzen, um deine Katzendaten elegant zu analysieren.",
    question: "Wie installierst und lädst du ein Paket in R?",
    code: null,
    options: [
      'install.packages("tidyverse") und dann library(tidyverse)',
      "import tidyverse",
      "pip install tidyverse",
      'require(install("tidyverse"))',
    ],
    correct: 0,
    explanation: "<code>install.packages()</code> lädt das Paket herunter (einmalig), <code>library()</code> aktiviert es in der Session. Beachte: install braucht Anführungszeichen, library nicht (kann aber).",
  },
  {
    section: "basics",
    category: "For-Schleife",
    context: "Du willst für jede deiner 5 Katzen einzeln eine Auswertung ausgeben.",
    question: "Welche Syntax hat eine for-Schleife in R?",
    code: null,
    options: [
      "for (katze in katzen_namen) { print(katze) }",
      "for katze in katzen_namen: print(katze)",
      "foreach (katze in katzen_namen) { print(katze) }",
      "for (katze : katzen_namen) { print(katze) }",
    ],
    correct: 0,
    explanation: 'R-Schleifen nutzen <code>for (var in vektor)</code> mit geschweiften Klammern. Aber: In R sind Schleifen oft langsamer als vektorisierte Operationen oder <code>apply()</code>-Funktionen.',
  },
  {
    section: "basics",
    category: "Sequenzen",
    context: "Du nummerierst deine 20 Versuchskatzen von 1 bis 20 durch.",
    question: "Welcher Code erzeugt eine Zahlenfolge von 1 bis 20?",
    code: null,
    options: [
      "1:20",
      "range(1, 20)",
      "seq(1, 20, 1)",
      "Sowohl A als auch C sind korrekt",
    ],
    correct: 3,
    explanation: "Sowohl <code>1:20</code> als auch <code>seq(1, 20, 1)</code> erzeugen die Zahlen 1 bis 20. <code>seq()</code> ist flexibler, z.B. <code>seq(0, 1, by=0.1)</code> für Dezimalschritte.",
  },

  // ========== DATEN & STRUKTUREN ==========
  {
    section: "daten",
    category: "Data Frames",
    context: "Du erstellst einen Datensatz mit Daten von Therapiekatzen: Name, Alter und Schnurr-Frequenz.",
    question: "Wie erstellst du einen Data Frame in R?",
    code: null,
    options: [
      'katzen <- data.frame(name=c("Luna","Milo"), alter=c(3,5), schnurr_hz=c(25,30))',
      'katzen <- dataframe(name=["Luna","Milo"], alter=[3,5])',
      "katzen <- new DataFrame(name, alter, schnurr_hz)",
      "katzen <- create_table(name, alter, schnurr_hz)",
    ],
    correct: 0,
    explanation: "<code>data.frame()</code> ist DIE zentrale Funktion für tabellarische Daten in R. Jede Spalte ist ein Vektor gleicher Länge. Beachte den Punkt in <code>data.frame</code> &mdash; typisch für Base-R!",
  },
  {
    section: "daten",
    category: "Subsetting",
    context: "Dein Datensatz <code>katzen</code> enthält 50 Katzen mit den Spalten: name, alter, spielzeit_min und schnurr_score.",
    question: "Wie filterst du nur Katzen, die älter als 5 sind?",
    code: null,
    options: [
      "katzen[katzen$alter > 5, ]",
      "katzen[alter > 5]",
      "katzen.filter(alter > 5)",
      "SELECT * FROM katzen WHERE alter > 5",
    ],
    correct: 0,
    explanation: 'Das <code>$</code>-Zeichen greift auf eine Spalte zu, die eckigen Klammern <code>[Zeilen, Spalten]</code> filtern den Data Frame. Das Komma vor der schließenden Klammer heißt: "alle Spalten".',
  },
  {
    section: "daten",
    category: "Faktoren",
    context: 'Du kodierst die Versuchsbedingungen deiner Katzenstudie: "Kontrolle", "Katzenminze", "Baldrian".',
    question: "Wie machst du daraus einen Faktor mit bestimmter Reihenfolge?",
    code: null,
    options: [
      'factor(bedingung, levels=c("Kontrolle", "Katzenminze", "Baldrian"))',
      'as.factor(bedingung, order=c("Kontrolle", "Katzenminze", "Baldrian"))',
      "ordered(bedingung)",
      'categorical(bedingung, levels=["Kontrolle", "Katzenminze", "Baldrian"])',
    ],
    correct: 0,
    explanation: "<code>factor()</code> mit dem Argument <code>levels</code> erstellt einen Faktor mit definierter Reihenfolge. Wichtig für die Reihenfolge in Grafiken und die Referenzkategorie in Regressionen.",
  },
  {
    section: "daten",
    category: "NA-Werte",
    context: "Katze Whiskers hat bei der dritten Messung geschlafen &mdash; kein Wert vorhanden.",
    question: "Was gibt <code>mean(stress)</code> zurück?",
    code: "stress <- c(3, 5, NA, 4, 6)\nmean(stress)",
    options: ["4.5", "NA", "4", "Error"],
    correct: 1,
    explanation: 'R gibt <code>NA</code> zurück, wenn NA-Werte enthalten sind &mdash; als Warnung, dass Daten fehlen. Lösung: <code>mean(stress, na.rm=TRUE)</code>. Das <code>na.rm</code> steht für "NA remove".',
  },
  {
    section: "daten",
    category: "Listen",
    context: "Du willst die Ergebnisse deiner Katzenstudie in einem Objekt speichern: numerische Werte, Text und einen Data Frame.",
    question: "Welche Datenstruktur kann verschiedene Datentypen enthalten?",
    code: null,
    options: [
      "list()",
      "c()",
      "data.frame()",
      "matrix()",
    ],
    correct: 0,
    explanation: "Eine <code>list()</code> kann beliebige Datentypen mischen: Zahlen, Text, Vektoren, Data Frames, sogar andere Listen. Vektoren (<code>c()</code>) erzwingen einen einheitlichen Typ.",
  },
  {
    section: "daten",
    category: "Spaltenzugriff",
    context: "Du hast einen Data Frame <code>katzen</code> und willst nur die Spalte mit den Namen extrahieren.",
    question: "Welche Methoden liefern die Spalte 'name' als Vektor?",
    code: null,
    options: [
      'katzen$name',
      'katzen["name"]',
      'katzen[, "name"]',
      'Sowohl A als auch C',
    ],
    correct: 3,
    explanation: '<code>katzen$name</code> und <code>katzen[, "name"]</code> liefern beide einen Vektor. <code>katzen["name"]</code> (ohne Komma) gibt dagegen einen Data Frame mit einer Spalte zurück.',
  },
  {
    section: "daten",
    category: "Daten einlesen",
    context: "Dein Betreuer schickt dir eine CSV-Datei mit Katzendaten: katzen_studie.csv.",
    question: "Wie liest du die CSV-Datei in R ein?",
    code: null,
    options: [
      'read.csv("katzen_studie.csv")',
      'open("katzen_studie.csv")',
      'import.csv("katzen_studie.csv")',
      'load("katzen_studie.csv")',
    ],
    correct: 0,
    explanation: '<code>read.csv()</code> ist die Standard-Funktion zum Einlesen von CSV-Dateien. Für europäische Formate (Semikolon als Trenner): <code>read.csv2()</code>. Im Tidyverse: <code>read_csv()</code>.',
  },
  {
    section: "daten",
    category: "Struktur prüfen",
    context: "Du hast einen neuen Datensatz geladen und willst schnell sehen, welche Spalten und Datentypen er hat.",
    question: "Welche Funktion zeigt die Struktur eines Objekts?",
    code: null,
    options: [
      "str(katzen)",
      "structure(katzen)",
      "info(katzen)",
      "describe(katzen)",
    ],
    correct: 0,
    explanation: "<code>str()</code> zeigt kompakt die Struktur: Datentyp, Dimensionen, Spaltentypen und erste Werte. Auch nützlich: <code>summary()</code> für deskriptive Statistiken und <code>head()</code> für die ersten Zeilen.",
  },

  // ========== STATISTIK ==========
  {
    section: "statistik",
    category: "Mittelwert",
    context: "Drei Katzen haben an einem Aufmerksamkeitstest teilgenommen. Reaktionszeiten: Muffin 3s, Whiskers 5s, Luna 7s.",
    question: "Was gibt dieser Code zurück?",
    code: "mean(c(3, 5, 7))",
    options: ["3", "5", "7", "15"],
    correct: 1,
    explanation: "<code>mean()</code> berechnet den Mittelwert. (3 + 5 + 7) / 3 = 5. Katze Whiskers lag also genau im Durchschnitt!",
  },
  {
    section: "statistik",
    category: "Standardabweichung",
    context: "Du willst wissen, wie stark die Zufriedenheitswerte deiner Therapiekatzen voneinander abweichen.",
    question: "Welche Funktion berechnet die Standardabweichung in R?",
    code: null,
    options: ["std(katzen_scores)", "sd(katzen_scores)", "stdev(katzen_scores)", "sigma(katzen_scores)"],
    correct: 1,
    explanation: '<code>sd()</code> steht für "standard deviation". R nutzt gerne kurze Funktionsnamen. Merkhilfe: <strong>S</strong>chnurrende <strong>D</strong>aten = sd().',
  },
  {
    section: "statistik",
    category: "Zufallszahlen",
    context: "Du simulierst IQ-Werte von 100 Katzen für deine Monte-Carlo-Studie. Katzen-IQ hat einen Mittelwert von 50 und eine SD von 10.",
    question: "Welcher Code erzeugt diese simulierten Daten?",
    code: null,
    options: [
      "rnorm(100, mean=50, sd=10)",
      "rnorm(mean=50, sd=10)",
      "norm(100, 50, 10)",
      "random.normal(100, 50, 10)",
    ],
    correct: 0,
    explanation: '<code>rnorm(n, mean, sd)</code> generiert <code>n</code> normalverteilte Zufallszahlen. Das "r" steht für "random". Es gibt auch <code>dnorm</code> (Dichte), <code>pnorm</code> (Verteilungsfunktion) und <code>qnorm</code> (Quantile).',
  },
  {
    section: "statistik",
    category: "t-Test",
    context: "Du vergleichst, ob Katzen mit klassischer Musik entspannter sind als Katzen mit Heavy Metal. Zwei Gruppen à 20 Katzen.",
    question: "Welcher Code führt einen unabhängigen t-Test durch?",
    code: null,
    options: [
      "t.test(klassik_scores, metal_scores)",
      "ttest(klassik_scores, metal_scores)",
      "t_test(klassik_scores ~ metal_scores)",
      "compare.means(klassik_scores, metal_scores)",
    ],
    correct: 0,
    explanation: "<code>t.test()</code> ist die Standardfunktion für t-Tests in R. Standardmäßig wird ein Welch-t-Test (ungleiche Varianzen) gerechnet. Für gepaarte Tests: <code>t.test(x, y, paired=TRUE)</code>.",
  },
  {
    section: "statistik",
    category: "Korrelation",
    context: "Du möchtest wissen, ob die tägliche Spielzeit einer Katze mit ihrem Glücksscore zusammenhängt.",
    question: "Wie berechnest du die Korrelation in R?",
    code: null,
    options: [
      "cor(spielzeit, glueck_score)",
      "correlation(spielzeit, glueck_score)",
      "pearson(spielzeit, glueck_score)",
      "r(spielzeit, glueck_score)",
    ],
    correct: 0,
    explanation: '<code>cor()</code> berechnet den Pearson-Korrelationskoeffizienten. Für Spearman: <code>cor(x, y, method="spearman")</code>. Für einen Signifikanztest: <code>cor.test(x, y)</code>.',
  },
  {
    section: "statistik",
    category: "Lineare Regression",
    context: "Du untersuchst, ob die tägliche Streichelzeit (UV) den Cortisolspiegel (AV) von Katzen vorhersagt.",
    question: "Welcher Code passt ein lineares Modell an?",
    code: null,
    options: [
      "lm(cortisol ~ streichelzeit, data=katzen)",
      "linear_model(cortisol, streichelzeit, data=katzen)",
      "lm(streichelzeit ~ cortisol, data=katzen)",
      "regression(cortisol ~ streichelzeit)",
    ],
    correct: 0,
    explanation: 'Die Formelschreibweise <code>AV ~ UV</code> liest sich als "AV wird vorhergesagt durch UV". Die abhängige Variable steht links. <code>lm()</code> = "linear model". Option C hat die Variablen vertauscht!',
  },
  {
    section: "statistik",
    category: "Shapiro-Wilk-Test",
    context: "Bevor du einen t-Test rechnest, prüfst du, ob die Schnurr-Frequenzen normalverteilt sind.",
    question: "Welcher Test prüft auf Normalverteilung in R?",
    code: null,
    options: [
      "shapiro.test(schnurr_hz)",
      "normal.test(schnurr_hz)",
      "ks.test(schnurr_hz)",
      "normality(schnurr_hz)",
    ],
    correct: 0,
    explanation: "<code>shapiro.test()</code> führt den Shapiro-Wilk-Test durch. Ein <em>nicht</em>-signifikantes Ergebnis (p > .05) bedeutet, dass die Daten nicht signifikant von der Normalverteilung abweichen.",
  },
  {
    section: "statistik",
    category: "ANOVA",
    context: "Du vergleichst drei Futtermarken (Premium, Standard, Budget) und deren Effekt auf das Gewicht von je 15 Katzen.",
    question: "Welcher Code führt eine einfaktorielle ANOVA durch?",
    code: null,
    options: [
      "aov(gewicht ~ futter, data=katzen)",
      "anova(gewicht, futter, data=katzen)",
      "oneway.test(gewicht, futter)",
      "f.test(gewicht ~ futter)",
    ],
    correct: 0,
    explanation: "<code>aov()</code> passt ein ANOVA-Modell an. Die Ergebnisse siehst du mit <code>summary()</code>. Für Post-hoc-Tests: <code>TukeyHSD(model)</code>. Die Formelschreibweise ist dieselbe wie bei <code>lm()</code>.",
  },
  {
    section: "statistik",
    category: "p-Wert interpretieren",
    context: "Dein t-Test ergibt p = 0.03. Du testest, ob Katzen mit Spielzeug glücklicher sind als ohne.",
    question: "Was bedeutet ein p-Wert von 0.03 bei alpha = 0.05?",
    code: "t.test(mit_spielzeug, ohne_spielzeug)\n# p-value = 0.03",
    options: [
      "Das Ergebnis ist statistisch signifikant",
      "Die Effektstärke ist groß",
      "Die Wahrscheinlichkeit, dass H0 wahr ist, beträgt 3%",
      "3% der Katzen sind glücklicher",
    ],
    correct: 0,
    explanation: "p < alpha (0.03 < 0.05) bedeutet, wir lehnen H0 ab &mdash; das Ergebnis ist statistisch signifikant. Der p-Wert sagt nichts über die Effektstärke oder die Wahrscheinlichkeit von H0 aus!",
  },
  {
    section: "statistik",
    category: "Chi-Quadrat-Test",
    context: "Du untersuchst, ob die Fellfarbe (schwarz/orange/grau) mit der Adoptionsrate (ja/nein) zusammenhängt.",
    question: "Welchen Test verwendest du für zwei kategoriale Variablen?",
    code: null,
    options: [
      "chisq.test(table(fellfarbe, adoptiert))",
      "chi.test(fellfarbe, adoptiert)",
      "fisher.test(fellfarbe, adoptiert)",
      "categorical.test(fellfarbe ~ adoptiert)",
    ],
    correct: 0,
    explanation: "<code>chisq.test()</code> führt einen Chi-Quadrat-Test durch. Die Daten müssen als Kreuztabelle (<code>table()</code>) vorliegen. Für kleine Stichproben: <code>fisher.test()</code>.",
  },

  // ========== VISUALISIERUNG ==========
  {
    section: "visualisierung",
    category: "ggplot2 Basics",
    context: "Du willst ein Streudiagramm: Spielzeit (x) gegen Schnurr-Frequenz (y) deiner 30 Versuchskatzen.",
    question: "Welcher ggplot2-Code erzeugt ein Streudiagramm?",
    code: null,
    options: [
      "ggplot(katzen, aes(x=spielzeit, y=schnurr_hz)) + geom_point()",
      "ggplot(katzen) + plot(spielzeit, schnurr_hz)",
      "plot.scatter(katzen, x=spielzeit, y=schnurr_hz)",
      "ggplot(katzen, aes(x=spielzeit, y=schnurr_hz)) + geom_scatter()",
    ],
    correct: 0,
    explanation: "ggplot2 baut Grafiken in Schichten auf: <code>ggplot()</code> definiert die Daten, <code>aes()</code> die Ästhetik (was auf welche Achse), und <code>geom_point()</code> zeichnet die Punkte. Es heißt <code>geom_point()</code>, nicht <code>geom_scatter()</code>!",
  },
  {
    section: "visualisierung",
    category: "Histogramm",
    context: "Du willst die Verteilung der Schnurr-Frequenzen deiner 100 Versuchskatzen visualisieren.",
    question: "Welcher ggplot2-Code erzeugt ein Histogramm?",
    code: null,
    options: [
      "ggplot(katzen, aes(x=schnurr_hz)) + geom_histogram()",
      "ggplot(katzen, aes(x=schnurr_hz)) + geom_bar()",
      "hist(katzen, schnurr_hz)",
      "ggplot(katzen) + histogram(schnurr_hz)",
    ],
    correct: 0,
    explanation: "<code>geom_histogram()</code> erzeugt ein Histogramm für kontinuierliche Daten. <code>geom_bar()</code> zählt Kategorien. Tipp: <code>bins=30</code> oder <code>binwidth=5</code> steuern die Balkenanzahl.",
  },
  {
    section: "visualisierung",
    category: "Boxplot",
    context: "Du vergleichst die Spielzeit pro Tag zwischen 3 Katzenrassen: Perser, Siam und Maine Coon.",
    question: "Welcher Code erzeugt einen Boxplot pro Rasse?",
    code: null,
    options: [
      "ggplot(katzen, aes(x=rasse, y=spielzeit)) + geom_boxplot()",
      "ggplot(katzen, aes(x=spielzeit)) + geom_boxplot(group=rasse)",
      "boxplot(katzen$spielzeit) + facet(rasse)",
      "ggplot(katzen) + geom_box(rasse, spielzeit)",
    ],
    correct: 0,
    explanation: "Für Boxplots pro Gruppe: die kategoriale Variable auf die x-Achse, die numerische auf y. <code>geom_boxplot()</code> zeichnet Median, Quartile und Ausreißer.",
  },
  {
    section: "visualisierung",
    category: "Farben & Gruppen",
    context: "Dein Streudiagramm soll die Punkte nach Geschlecht der Katze einfärben: männlich vs. weiblich.",
    question: "Wie fügst du Farbgruppierung hinzu?",
    code: null,
    options: [
      "ggplot(katzen, aes(x=alter, y=gewicht, color=geschlecht)) + geom_point()",
      'ggplot(katzen, aes(x=alter, y=gewicht)) + geom_point(color="geschlecht")',
      "ggplot(katzen, aes(x=alter, y=gewicht)) + geom_point() + color(geschlecht)",
      "ggplot(katzen, aes(x=alter, y=gewicht)) + geom_point(group=geschlecht)",
    ],
    correct: 0,
    explanation: 'In ggplot2 kommt <code>color=variable</code> in <code>aes()</code>, damit die Farbe datenabhängig ist. Außerhalb von <code>aes()</code> setzt <code>color="red"</code> eine feste Farbe.',
  },
  {
    section: "visualisierung",
    category: "Facetten",
    context: "Du willst für jede Futtermarke ein separates Histogramm der Gewichtszunahme deiner Katzen.",
    question: "Wie erzeugst du separate Panels in ggplot2?",
    code: null,
    options: [
      "ggplot(katzen, aes(x=gewicht)) + geom_histogram() + facet_wrap(~futter)",
      "ggplot(katzen, aes(x=gewicht)) + geom_histogram() + split_by(futter)",
      "ggplot(katzen, aes(x=gewicht)) + geom_histogram() + panels(futter)",
      "ggplot(katzen, aes(x=gewicht, facet=futter)) + geom_histogram()",
    ],
    correct: 0,
    explanation: "<code>facet_wrap(~variable)</code> erstellt ein Panel pro Gruppe. Für zwei Variablen: <code>facet_grid(zeile ~ spalte)</code>. Die Tilde <code>~</code> ist die Formelschreibweise.",
  },
  {
    section: "visualisierung",
    category: "Achsenbeschriftung",
    context: "Dein Plot braucht noch einen Titel und Achsenbeschriftungen für die Publikation.",
    question: "Wie fügst du Titel und Achsenlabels hinzu?",
    code: null,
    options: [
      'labs(title="Katzengewicht", x="Alter (Jahre)", y="Gewicht (kg)")',
      'title("Katzengewicht") + xlabel("Alter") + ylabel("Gewicht")',
      'ggtitle("Katzengewicht", xlab="Alter", ylab="Gewicht")',
      'label(title="Katzengewicht", axes=c("Alter", "Gewicht"))',
    ],
    correct: 0,
    explanation: "<code>labs()</code> ist die universelle Funktion für Beschriftungen in ggplot2. Du kannst auch <code>xlab()</code>, <code>ylab()</code> und <code>ggtitle()</code> einzeln verwenden.",
  },
  {
    section: "visualisierung",
    category: "Themes",
    context: "Dein Betreuer will einen cleanen Look ohne den grauen Hintergrund von ggplot2.",
    question: "Welches Theme entfernt den grauen Hintergrund?",
    code: null,
    options: [
      "theme_minimal()",
      "theme_clean()",
      "theme_none()",
      "remove_background()",
    ],
    correct: 0,
    explanation: "<code>theme_minimal()</code> gibt einen sauberen Look. Weitere beliebte Themes: <code>theme_classic()</code> (wie Base-R), <code>theme_bw()</code> (schwarz-weiß) und <code>theme_void()</code> (komplett leer).",
  },
  {
    section: "visualisierung",
    category: "Plot speichern",
    context: "Dein fertiges Katzendiagramm soll als hochauflösendes PNG für die Bachelorarbeit gespeichert werden.",
    question: "Wie speicherst du einen ggplot?",
    code: null,
    options: [
      'ggsave("katzen_plot.png", width=8, height=6, dpi=300)',
      'save.plot("katzen_plot.png")',
      'export(plot, "katzen_plot.png")',
      'png.save(plot, "katzen_plot.png")',
    ],
    correct: 0,
    explanation: '<code>ggsave()</code> speichert den letzten ggplot. Du kannst Format (png, pdf, svg), Größe und Auflösung angeben. Für Publikationen: <code>dpi=300</code> ist Standard.',
  },

  // ========== TIDYVERSE ==========
  {
    section: "tidyverse",
    category: "Pipe-Operator",
    context: "Du willst deine Katzendaten filtern, gruppieren und zusammenfassen &mdash; alles in einer lesbaren Pipeline.",
    question: "Welches Symbol ist der Pipe-Operator im tidyverse?",
    code: "katzen ___\n  filter(alter > 2) ___\n  group_by(rasse) ___\n  summarise(mean_schnurr = mean(schnurr_hz))",
    options: ["|>", "%>%", ">>", "->"],
    correct: 1,
    explanation: "<code>%>%</code> ist der magrittr-Pipe-Operator aus dem tidyverse. Er leitet das Ergebnis links als erstes Argument in die Funktion rechts. Seit R 4.1 gibt es auch den nativen Pipe <code>|></code>.",
  },
  {
    section: "tidyverse",
    category: "filter()",
    context: "Du willst nur Katzen auswählen, die älter als 3 Jahre und schwerer als 4 kg sind.",
    question: "Welcher dplyr-Code filtert korrekt?",
    code: null,
    options: [
      "katzen %>% filter(alter > 3, gewicht > 4)",
      "katzen %>% filter(alter > 3 AND gewicht > 4)",
      "katzen %>% where(alter > 3, gewicht > 4)",
      "katzen %>% subset(alter > 3 & gewicht > 4)",
    ],
    correct: 0,
    explanation: "In <code>filter()</code> werden mehrere Bedingungen mit Komma getrennt (implizites UND). Du kannst auch <code>&</code> verwenden. <code>|</code> steht für ODER.",
  },
  {
    section: "tidyverse",
    category: "mutate()",
    context: "Du willst eine neue Spalte berechnen: den BMI jeder Katze (Gewicht / Länge²).",
    question: "Welche dplyr-Funktion erstellt neue Spalten?",
    code: null,
    options: [
      "katzen %>% mutate(bmi = gewicht / laenge^2)",
      "katzen %>% add_column(bmi = gewicht / laenge^2)",
      "katzen %>% transform(bmi = gewicht / laenge^2)",
      "katzen %>% calculate(bmi = gewicht / laenge^2)",
    ],
    correct: 0,
    explanation: "<code>mutate()</code> erstellt neue Spalten oder verändert bestehende. Der Datensatz bleibt vollständig erhalten. Für nur die neue Spalte: <code>transmute()</code>.",
  },
  {
    section: "tidyverse",
    category: "summarise()",
    context: "Du willst den Mittelwert und die SD der Spielzeit pro Katzenrasse berechnen.",
    question: "Welcher Code gruppiert und fasst zusammen?",
    code: null,
    options: [
      "katzen %>% group_by(rasse) %>% summarise(m = mean(spielzeit), s = sd(spielzeit))",
      "katzen %>% group(rasse) %>% summary(m = mean(spielzeit))",
      "katzen %>% summarise(mean(spielzeit), by=rasse)",
      "katzen %>% aggregate(spielzeit ~ rasse, mean)",
    ],
    correct: 0,
    explanation: "Die Kombination <code>group_by() %>% summarise()</code> ist das Herzstück von dplyr. Erst gruppieren, dann pro Gruppe zusammenfassen. Du kannst beliebig viele Statistiken berechnen.",
  },
  {
    section: "tidyverse",
    category: "select()",
    context: "Dein Katzendatensatz hat 20 Spalten, aber du brauchst nur name, alter und schnurr_hz.",
    question: "Wie wählst du nur bestimmte Spalten aus?",
    code: null,
    options: [
      "katzen %>% select(name, alter, schnurr_hz)",
      "katzen %>% columns(name, alter, schnurr_hz)",
      "katzen %>% pick(name, alter, schnurr_hz)",
      "katzen[, c(name, alter, schnurr_hz)]",
    ],
    correct: 0,
    explanation: "<code>select()</code> wählt Spalten aus. Nützliche Helfer: <code>starts_with()</code>, <code>ends_with()</code>, <code>contains()</code>. Zum Entfernen: <code>select(-spalte)</code>.",
  },
  {
    section: "tidyverse",
    category: "arrange()",
    context: "Du willst deine Katzen nach Gewicht sortieren, die schwersten zuerst.",
    question: "Welcher Code sortiert absteigend?",
    code: null,
    options: [
      "katzen %>% arrange(desc(gewicht))",
      "katzen %>% sort(gewicht, decreasing=TRUE)",
      "katzen %>% order_by(-gewicht)",
      "katzen %>% arrange(gewicht, reverse=TRUE)",
    ],
    correct: 0,
    explanation: "<code>arrange()</code> sortiert aufsteigend. Für absteigend: <code>desc()</code> um die Variable wickeln. Du kannst auch nach mehreren Spalten sortieren: <code>arrange(rasse, desc(gewicht))</code>.",
  },
  {
    section: "tidyverse",
    category: "pivot_longer()",
    context: "Dein Datensatz hat die Spalten: katze, montag_spielzeit, dienstag_spielzeit, mittwoch_spielzeit. Du willst ihn ins Long-Format bringen.",
    question: "Welche Funktion wandelt Wide- in Long-Format um?",
    code: null,
    options: [
      "pivot_longer()",
      "melt()",
      "gather()",
      "reshape()",
    ],
    correct: 0,
    explanation: '<code>pivot_longer()</code> ist die moderne tidyr-Funktion. <code>gather()</code> war der Vorgänger (deprecated). Umgekehrt: <code>pivot_wider()</code> macht Long zu Wide.',
  },
  {
    section: "tidyverse",
    category: "left_join()",
    context: "Du hast zwei Datensätze: katzen_info (Name, Rasse) und katzen_tests (Name, Score). Du willst sie zusammenführen.",
    question: "Welcher Join behält alle Zeilen aus dem linken Datensatz?",
    code: null,
    options: [
      'left_join(katzen_info, katzen_tests, by="name")',
      'merge(katzen_info, katzen_tests, on="name")',
      'join(katzen_info, katzen_tests, key="name")',
      'katzen_info %>% attach(katzen_tests, by="name")',
    ],
    correct: 0,
    explanation: '<code>left_join()</code> behält alle Zeilen aus dem linken Datensatz und fügt passende Werte aus dem rechten hinzu. Kein Match = NA. Weitere: <code>inner_join()</code>, <code>full_join()</code>, <code>right_join()</code>.',
  },
];

const CORRECT_GIFS = [
  "https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif",
  "https://media.giphy.com/media/3oriO0OEd9QIDdllqo/giphy.gif",
  "https://media.giphy.com/media/ICOgUNjpvO0PC/giphy.gif",
  "https://media.giphy.com/media/MDJ9IbxxvDUQM/giphy.gif",
  "https://media.giphy.com/media/l0HlPwMAzh13QYR7q/giphy.gif",
  "https://media.giphy.com/media/nR4L10XlJcSeQ/giphy.gif",
  "https://media.giphy.com/media/mlvseq9ysyG7K/giphy.gif",
  "https://media.giphy.com/media/5i7IUqyOtTnSU/giphy.gif",
];

const WRONG_GIFS = [
  "https://media.giphy.com/media/JYZ397GqraYA8/giphy.gif",
  "https://media.giphy.com/media/VbnUQpnihPSIgIXuZv/giphy.gif",
  "https://media.giphy.com/media/3o7527pa7qs4kEq3Hq/giphy.gif",
  "https://media.giphy.com/media/bEVKYB487Lqxy/giphy.gif",
  "https://media.giphy.com/media/3o6Zt481isNVuQI1l6/giphy.gif",
  "https://media.giphy.com/media/xT0xeMA62E1XIlup6g/giphy.gif",
  "https://media.giphy.com/media/melZPISQa99Is/giphy.gif",
  "https://media.giphy.com/media/H4DjXQXamtTiIuCcRU/giphy.gif",
];

const CAT_FACTS = [
  "Katzen schlafen 12-16 Stunden pro Tag — also ca. die Hälfte ihres Lebens. Genau wie Psychologie-Studierende in der Statistik-Vorlesung.",
  "Hauskatzen können im Sprint bis zu 48 km/h schnell laufen. Ungefähr so schnell, wie du vor der Statistik-Klausur wegrennen willst.",
  "Das Schnurren einer Katze liegt zwischen 25-150 Hz. Einige Studien deuten auf positive Effekte für die Knochenheilung hin — aber die Evidenz ist noch nicht eindeutig.",
  "Katzen haben 230 Knochen, Menschen nur 206. Mehr Knochen = mehr Freiheitsgrade. Statistiker-Humor.",
  "Nikola Tesla schrieb in einem Brief, dass seine Kindheitskatze Macak ihn erstmals für Elektrizität begeistert hat.",
  "Schätzungen zufolge gibt es 400-600 Millionen Hauskatzen weltweit. Das ist eine ordentliche Stichprobe!",
  "Katzen können ihren Körper um 180 Grad drehen — dank ihrer extrem flexiblen Wirbelsäule. Ähnlich wie manche Forschungsergebnisse nach einem Review.",
  "Das Katzengehirn hat eine ähnliche Grundstruktur wie das menschliche — mit Großhirnrinde, Hippocampus und Amygdala. Mini-Psychologen!",
  "Katzen können über 100 verschiedene Laute erzeugen. Hunde nur etwa 10. Katzen haben die höhere Effektstärke.",
  "Der älteste bekannte Hauskatzenfund stammt aus Zypern und ist ca. 9.500 Jahre alt. Langzeitstudie!",
  "Katzen schlafen 12-16 Stunden pro Tag. Das ist der wahre Work-Life-Balance-Experte.",
  'Eine Gruppe Katzen heißt übrigens "Clowder". Nein, das ist kein statistischer Begriff.',
  "Katzen können Ultraschall hören — bis zu 64 kHz, dreimal höher als Menschen. Vielleicht hören sie auch den p-Wert fallen.",
  "Deutschland hat mit über 15 Millionen die meisten Hauskatzen in Europa. Frankreich kommt auf Platz zwei.",
  "Katzen verbringen 30-50% ihres Tages mit Fellpflege. Selbstfürsorge auf höchstem Niveau.",
  "Die Geschichte, dass Newton die Katzenklappe erfand, ist ein beliebter Mythos — es gibt dafür keinen historischen Beleg. Trotzdem eine nette Geschichte.",
  "Eine Katze hat pro Ohr 32 Muskeln. Mit so vielen Variablen könntest du ein schönes Regressionsmodell bauen.",
  "Hauskatzen teilen 95,6% ihrer DNA mit Tigern. Effektstärke: riesig.",
  "Katzen sehen bei wenig Licht ca. 6-8x besser als Menschen — dank einer reflektierenden Schicht (Tapetum lucidum) hinter der Netzhaut.",
  "Katzen haben ein ausgezeichnetes räumliches Gedächtnis — sie merken sich Orte und Verstecke oft über Monate hinweg.",
];

const RESULT_TIERS = [
  { min: 90, mascot: "😻", title: "Professor Schnurrbart!", desc: "Du bist die absolute Katzen-Koryphäe der R-Programmierung. Deine p-Werte sind immer signifikant und deine Katzen immer zufrieden." },
  { min: 70, mascot: "😸", title: "Doktorkatze!", desc: "Sehr beeindruckend! Du kennst dich gut aus. Noch ein paar Streicheleinheiten (Übungen) und du bist ganz oben." },
  { min: 50, mascot: "🐱", title: "Fleißiges Kätzchen!", desc: "Solide Grundlagen! Du bist auf dem richtigen Weg. Übe weiter und du wirst bald zum Statistik-Tiger." },
  { min: 30, mascot: "🙀", title: "Verwirrtes Kätzchen!", desc: "Noch etwas unsicher, aber keine Sorge! Auch die klügste Katze hat mal klein angefangen. Versuch es nochmal!" },
  { min: 0, mascot: "😿", title: "Verschlafenes Kätzchen...", desc: "Hast du während des Quiz ein Nickerchen gemacht? Kein Problem, Katzen brauchen Wiederholungen. Probier es nochmal!" },
];

const STREAK_MESSAGES = {
  3: "🔥 3er Streak!",
  4: "🔥🔥 4er Streak!",
  5: "🔥🔥🔥 FEUER!",
  6: "😺 UNAUFHALTBAR!",
  7: "🐱‍👤 KATZEN-GENIE!",
};
